# Generated by Django 3.0.7 on 2021-03-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='files',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
