# Generated by Django 3.0.7 on 2021-03-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0002_auto_20210311_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='xml',
        ),
    ]
