# Generated by Django 3.0.7 on 2021-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0003_remove_files_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
