# Generated by Django 3.0.7 on 2021-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIapp', '0005_delete_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('xml', models.FileField(upload_to='')),
            ],
        ),
    ]
