# Generated by Django 3.0.7 on 2021-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0006_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=200)),
                ('obj_name', models.CharField(max_length=100)),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('ts', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
